<a href="https://colab.research.google.com/github/Arghyajyoti007/Pandas-Overview/blob/main/customer_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **CLEANING PROCESS**

In [20]:
import pandas as pd
df = pd.read_csv("/content/messy_customer_sales_data.csv")
display(df)

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
0,CUST4371,Paul Wilson,m,52.0,KOLKATA,2025-06-26,2025-05-17,26944.0,1.0,peckvictoria@example.com,2131107701,India
1,CUST5957,Jason Thomas,M,51.0 years,NaN,2021-02-17,2025-07-22,44152.0,2.0,owensanthony@example.com,1080761560,india
2,CUST3754,Brittney Martinez,F,62.0,hyderabad,2023-11-05,2024-12-08,31745.0,2.0,tara39@example.org,8981006345,India
3,CUST2934,Brenda Pierce,FEMALE,40.0,hyderabad,2022-03-13,2025-10-02,39674.0,1.0,berrynancy@example.org,8228064204,india
4,CUST5683,Matthew Carroll,f,41.0,CHENNAI,2024-04-05,2024-12-15,NaN,8.0,denise84@example.org,2665569480,India
...,...,...,...,...,...,...,...,...,...,...,...,...
10195,CUST10767,Robert Lewis,female,35.0 years,delhi,2020-12-08,2025-01-25,24167.0,9.0,barrycrane@example.net,5004696571,InDia
10196,NaN,Diane Evans,M,53.0,bangalore,2023-12-31,2025-05-07,11639.0,7.0,lisadennis@example.net,5200349941,IND
10197,CUST6315,Joshua Martinez,m,25.0,hyderabad,2022-02-15,2025-01-11,43832.0,2.0,kelli74@example.org,8147428496,India
10198,CUST4812,Sarah Miller,FEMALE,55.0,NaN,2021-03-16,2025-05-14,18827.0,10.0,dawn84@example.org,2987564247,InDia
10199,CUST6588,David Potter,female,34.0,HYDERABAD,2020-10-12,2025-06-27,35211.0,10.0,kochjonathan@example.org,1926206725,India

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10200 entries, 0 to 10199
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         9177 non-null   object
 1   Name                10200 non-null  object
 2   Gender              9174 non-null   object
 3   Age                 9249 non-null   object
 4   City                9184 non-null   object
 5   Signup_Date         10200 non-null  object
 6   Last_Purchase_Date  9188 non-null   object
 7   Purchase_Amount     9179 non-null   float64
 8   Feedback_Score      9177 non-null   float64
 9   Email               10200 non-null  object
 10  Phone_Number        10200 non-null  int64
 11  Country             9468 non-null   object
dtypes: float64(2), int64(1), object(9)
memory usage: 956.4+ KB

In [22]:
df.isnull().sum()

Customer_ID           1023
Name                     0
Gender                1026
Age                    951
City                  1016
Signup_Date              0
Last_Purchase_Date    1012
Purchase_Amount       1021
Feedback_Score        1023
Email                    0
Phone_Number             0
Country                732
dtype: int64

In [23]:
df.isnull().sum()/len(df)*100

Customer_ID           10.029412
Name                   0.000000
Gender                10.058824
Age                    9.323529
City                   9.960784
Signup_Date            0.000000
Last_Purchase_Date     9.921569
Purchase_Amount       10.009804
Feedback_Score        10.029412
Email                  0.000000
Phone_Number           0.000000
Country                7.176471
dtype: float64

In [24]:
df.describe().round()

       Purchase_Amount  Feedback_Score  Phone_Number
count           9179.0          9177.0  1.020000e+04
mean           29090.0             5.0  4.979974e+09
std           208697.0             3.0  2.902593e+09
min             -500.0             1.0  9.208990e+05
25%            12295.0             3.0  2.449157e+09
50%            24330.0             5.0  4.988639e+09
75%            37130.0             8.0  7.510448e+09
max          9999999.0            10.0  9.994402e+09

In [25]:
df.shape

(10200, 12)

In [26]:
df.dropna().shape

(4528, 12)

In [27]:
df[df.duplicated()].shape

(15, 12)

In [28]:
df[df.duplicated()]

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
2032,CUST2755,Casey Campbell,male,NaN,Hyderabad,2023-12-01,2024-11-04,11778.0,3.0,joseph49@example.com,3844741384,India
3191,NaN,Travis Schneider,f,51.0,NaN,2025-04-20,2025-02-28,48750.0,5.0,bianca77@example.net,7623118785,India
4312,CUST8305,Stanley Cain,FEMALE,51.0,Bangalore,2023-08-14,2024-11-01,11432.0,6.0,calderonbrenda@example.org,4889366037,India
5611,CUST6288,Jonathon Kim,male,46.0,Chennai,2023-11-22,2025-03-21,3301.0,6.0,tparker@example.com,5266662560,India
5680,CUST2695,Lisa Durham,NaN,46.0,Chennai,2021-04-18,2024-10-10,6511.0,3.0,andrew34@example.com,2235480149,India
5899,CUST8841,Amanda Hill,NaN,34.0,chennai,2022-09-11,2025-03-13,42092.0,4.0,ryanriley@example.net,3466026146,India
6070,CUST10780,Emily Smith,NaN,23.0,Kolkata,2023-12-09,2024-10-28,18027.0,5.0,perezchristopher@example.com,3032282870,India
6240,CUST9745,David Morales,NaN,56.0,NaN,2023-02-18,2024-12-14,49107.0,7.0,juliaknapp@example.com,9436163110,India
6425,CUST4631,George Villa,m,26.0,Mumbai,2022-05-21,2025-06-17,NaN,8.0,davidmarquez@example.com,8869465862,India
6498,CUST1711,Stephanie Elliott,NaN,44.0,MUMBAI,2023-05-17,2025-07-12,11349.0,9.0,nfischer@example.com,3270872546,NaN
7118,CUST9380,Paul Wilson,MALE,42.0,Bangalore,2025-07-31,2025-09-21,2696.0,5.0,steven57@example.net,6835989909,India
8392,CUST1436,Ralph Anderson,female,33.0,Kolkata,2022-10-21,2025-04-24,42870.0,NaN,vcosta@example.com,3739220307,India
9155,CUST10040,Mark Taylor,NaN,43.0,Delhi,2021-04-16,2025-01-13,37793.0,6.0,tinaknapp@example.org,9898365939,India
9960,CUST6220,John Rodriguez,male,51.0,Hyderabad,2021-03-28,2025-01-22,27102.0,10.0,laurahart@example.com,7462990833,India
10140,CUST4367,Amber Kennedy,F,61.0,Bangalore,2023-11-05,2025-01-10,40711.0,8.0,kellifox@example.com,5600790669,India

In [29]:
df['Customer_ID'].value_counts().head()

Customer_ID
CUST10800    2
CUST6588     2
CUST9062     2
CUST1852     2
CUST5472     2
Name: count, dtype: int64

In [30]:
df[df['Customer_ID']=='CUST10800']

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
3986,CUST10800,Kevin Clark,F,52.0,Bangalore,2021-06-29,2025-09-12,34914.0,10.0,sandycarey@example.net,2719399414,India
10103,CUST10800,Kevin Clark,female,52.0,Bangalore,2021-06-29,2025-09-12,34914.0,10.0,sandycarey@example.net,2719399414,india

In [31]:
for col in df.columns:
  if df[col].nunique() < 20:
    print(df[col].value_counts())
    print("-"*50)

Gender
f         1184
M         1171
m         1163
F         1157
MALE      1131
female    1128
male      1121
FEMALE    1119
Name: count, dtype: int64
--------------------------------------------------
City
Kolkata       820
Mumbai        812
Chennai       784
Bangalore     773
Hyderabad     770
Delhi         763
CHENNAI       404
KOLKATA       395
MUMBAI        393
hyderabad     384
bangalore     383
DELHI         378
delhi         369
BANGALORE     363
HYDERABAD     360
mumbai        352
chennai       343
kolkata       338
Name: count, dtype: int64
--------------------------------------------------
Feedback_Score
2.0     952
4.0     947
7.0     938
6.0     927
3.0     913
8.0     912
1.0     907
9.0     903
10.0    901
5.0     877
Name: count, dtype: int64
--------------------------------------------------
Country
India    7132
IND       793
india     772
InDia     771
Name: count, dtype: int64
--------------------------------------------------

# **HANDELING MISSING VALUES**

In [32]:
df.dropna(subset = ['Customer_ID'], inplace = True)

In [33]:
df.shape

(9177, 12)

In [34]:
df.isnull().sum()

Customer_ID             0
Name                    0
Gender                934
Age                   859
City                  918
Signup_Date             0
Last_Purchase_Date    914
Purchase_Amount       927
Feedback_Score        905
Email                   0
Phone_Number            0
Country               664
dtype: int64

In [35]:
df['Age'].unique()

array(['52.0', '51.0 years', '62.0', '40.0', '41.0', nan, '18.0',
       '43.0 years', '40.0 years', '26.0', '32.0', '22.0', '59.0', '65.0',
       '61.0', '31.0', '54.0 years', '55.0', '69.0', '61.0 years', '24.0',
       '63.0', '19.0', '50.0', '56.0', '36.0', '68.0', '43.0', '38.0',
       '27.0', '57.0 years', '23.0', '25.0', '66.0', '28.0', '30.0',
       '46.0', '48.0', '20.0', '37.0', '67.0', '51.0', '35.0', '58.0',
       '29.0', 'nan years', '39.0', '49.0', '47.0', '42.0', '44.0',
       '64.0', '53.0', '60.0', '59.0 years', '45.0', '21.0', '34.0',
       '54.0', '48.0 years', '46.0 years', '33.0', '57.0', '30.0 years',
       '58.0 years', '35.0 years', '34.0 years', '69.0 years', '250',
       '19.0 years', '27.0 years', '53.0 years', '65.0 years',
       '66.0 years', '44.0 years', '49.0 years', '25.0 years',
       '23.0 years', '62.0 years', '41.0 years', '33.0 years',
       '28.0 years', '22.0 years', '20.0 years', '42.0 years',
       '45.0 years', '3', '63.0 years', '37.0 years', '38.0 years',
       '55.0 years', '18.0 years', '36.0 years', '67.0 years',
       '29.0 years', '39.0 years', '31.0 years', '47.0 years',
       '52.0 years', '-10', '60.0 years', '24.0 years', '26.0 years',
       '21.0 years', '64.0 years', '50.0 years', '68.0 years',
       '32.0 years', '56.0 years'], dtype=object)

In [36]:
import re

def extract_age(age):
  age_num = re.findall('[0-9]+', str(age))
  if len(age_num) > 0 :
    return age_num[0]
  else:
    return age

df['Age'] = df['Age'].apply(lambda x : extract_age(x))

In [37]:
df['Age'].unique()

array(['52', '51', '62', '40', '41', nan, '18', '43', '26', '32', '22',
       '59', '65', '61', '31', '54', '55', '69', '24', '63', '19', '50',
       '56', '36', '68', '38', '27', '57', '23', '25', '66', '28', '30',
       '46', '48', '20', '37', '67', '35', '58', '29', 'nan years', '39',
       '49', '47', '42', '44', '64', '53', '60', '45', '21', '34', '33',
       '250', '3', '10'], dtype=object)

In [38]:
df_age = df[df['Age'] != 'nan years']['Age']
age_median = int(df_age.dropna().astype('int64').median())
print(age_median)
df.replace('nan years', age_median, inplace = True)
df['Age'].fillna(age_median, inplace = True)

43

/tmp/ipykernel_3732/3614585136.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(age_median, inplace = True)

In [39]:
df.isnull().sum()

Customer_ID             0
Name                    0
Gender                934
Age                     0
City                  918
Signup_Date             0
Last_Purchase_Date    914
Purchase_Amount       927
Feedback_Score        905
Email                   0
Phone_Number            0
Country               664
dtype: int64

In [40]:
for col in ['City','Country','Gender']:
  df[col].fillna(df[col].mode()[0], inplace=True)

/tmp/ipykernel_3732/1423800374.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [41]:
df['Purchase_Amount'].fillna(df['Purchase_Amount'].median(), inplace = True)

/tmp/ipykernel_3732/1105428469.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Purchase_Amount'].fillna(df['Purchase_Amount'].median(), inplace = True)

In [42]:
df['Feedback_Score'].fillna(df['Feedback_Score'].mode()[0], inplace = True)

/tmp/ipykernel_3732/1221350052.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Feedback_Score'].fillna(df['Feedback_Score'].mode()[0], inplace = True)

In [43]:
df['Last_Purchase_Date'].ffill(inplace = True)

/tmp/ipykernel_3732/2735699428.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Last_Purchase_Date'].ffill(inplace = True)

In [44]:
df.isnull().sum()

Customer_ID           0
Name                  0
Gender                0
Age                   0
City                  0
Signup_Date           0
Last_Purchase_Date    0
Purchase_Amount       0
Feedback_Score        0
Email                 0
Phone_Number          0
Country               0
dtype: int64

# **FIXING INCONSISTENT FORMATING**

In [45]:
df['Gender'].unique()

array(['m ', 'M', 'F', 'FEMALE', 'f ', 'male', 'MALE', 'female'],
      dtype=object)

In [46]:
df['Gender'] = df['Gender'].str.lower().str.strip()

In [47]:
df['Gender'].replace({'f':'female','m':'male'}, inplace=True)

/tmp/ipykernel_3732/2862295434.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gender'].replace({'f':'female','m':'male'}, inplace=True)

In [48]:
df['Gender'].unique()

array(['male', 'female'], dtype=object)

In [49]:
df['City'].unique()

array([' KOLKATA ', ' Kolkata ', ' hyderabad ', ' CHENNAI ', ' kolkata ',
       ' BANGALORE ', ' Hyderabad ', ' HYDERABAD ', ' Mumbai ',
       ' chennai ', ' Delhi ', ' bangalore ', ' Bangalore ', ' delhi ',
       ' Chennai ', ' MUMBAI ', ' DELHI ', ' mumbai '], dtype=object)

In [50]:
df['City'] = df['City'].str.strip().str.lower()

In [51]:
df['Country'].unique()

array(['India', 'india', 'InDia', 'IND'], dtype=object)

In [52]:
df['Country'] = df['Country'].str.strip().str.lower()

In [53]:
df['Country'].replace({'ind':'india'}, inplace=True)

/tmp/ipykernel_3732/3232952229.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Country'].replace({'ind':'india'}, inplace=True)

# **HANDLING DUPLICATES**

In [54]:
df[df.duplicated()].shape

(163, 12)

In [55]:
df.drop_duplicates(inplace = True)

In [56]:
df['Customer_ID'].value_counts()

Customer_ID
CUST6069    2
CUST9950    2
CUST7652    2
CUST5341    2
CUST2510    2
           ..
CUST6618    1
CUST2244    1
CUST6807    1
CUST2355    1
CUST8117    1
Name: count, Length: 9000, dtype: int64

In [57]:
df[df['Customer_ID']=='CUST6069']

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
586,CUST6069,Brian Daniel,male,20,delhi,2024-06-16,2025-08-23,924.0,10.0,adamalvarez@example.org,3672728121,india
5788,CUST6069,Brian Daniel,male,20,delhi,2024-06-16,2025-02-09,924.0,10.0,adamalvarez@example.org,3672728121,india

In [58]:
df.drop_duplicates(subset = 'Customer_ID', keep = 'first', inplace = True)

In [59]:
df.shape

(9000, 12)

# **CORRECT DATA TYPE**

In [60]:
df.describe()

       Purchase_Amount  Feedback_Score  Phone_Number
count     9.000000e+03     9000.000000  9.000000e+03
mean      2.908195e+04        5.138222  4.983041e+09
std       2.107046e+05        2.909916  2.901555e+09
min      -5.000000e+02        1.000000  9.208990e+05
25%       1.383000e+04        2.000000  2.449808e+09
50%       2.426800e+04        5.000000  4.998591e+09
75%       3.567125e+04        8.000000  7.510124e+09
max       9.999999e+06       10.000000  9.994402e+09

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9000 entries, 0 to 10198
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         9000 non-null   object
 1   Name                9000 non-null   object
 2   Gender              9000 non-null   object
 3   Age                 9000 non-null   int64
 4   City                9000 non-null   object
 5   Signup_Date         9000 non-null   datetime64[ns]
 6   Last_Purchase_Date  9000 non-null   datetime64[ns]
 7   Purchase_Amount     9000 non-null   float64
 8   Feedback_Score      9000 non-null   float64
 9   Email               9000 non-null   object
 10  Phone_Number        9000 non-null   int64
 11  Country             9000 non-null   object
dtypes: datetime64[ns](2), float64(2), int64(2), object(6)
memory usage: 914.1+ KB

In [64]:
df['Age']=df['Age'].astype('int64')

In [68]:
df['Last_Purchase_Date'] = pd.to_datetime(df['Last_Purchase_Date'])
df['Signup_Date'] = pd.to_datetime(df['Signup_Date'])

# **HANDLING OUTLIERS**

In [70]:
import numpy as np
from scipy import stats

In [82]:
z_scores = np.abs(stats.zscore(df[['Age','Purchase_Amount']]))
threshold = 3
df_clean = df[~(z_scores > threshold).any(axis = 1)]
df_clean.shape
df_clean.describe()

,Age,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Phone_Number
count,8989.000000,8989,8989,8989.000000,8989.000000,8.989000e+03
mean,43.418845,2023-04-12 06:36:29.075536640,2025-04-08 11:24:02.162643200,24654.581266,5.138280,4.984198e+09
min,3.000000,2020-10-08 00:00:00,2024-10-08 00:00:00,-500.000000,1.000000,9.208990e+05
25%,32.000000,2022-01-17 00:00:00,2025-01-07 00:00:00,13831.000000,2.000000,2.452541e+09
50%,43.000000,2023-04-05 00:00:00,2025-04-10 00:00:00,24268.000000,5.000000,4.999279e+09
75%,55.000000,2024-07-12 00:00:00,2025-07-08 00:00:00,35660.000000,8.000000,7.511245e+09
max,69.000000,2025-10-08 00:00:00,2025-10-08 00:00:00,49992.000000,10.000000,9.994402e+09
std,14.205506,NaN,NaN,13622.638940,2.909729,2.901468e+09

# **SAVE CLEANED DATA**

In [83]:
df_clean.to_csv('cleaned_customer_sales_data.csv', index = False)